version: '3'

services:

# FRONTEND
  frontend:
    image: node:latest
    container_name: pacmail-frontend
    working_dir: /frontend
    restart: always
    env_file:
      - ./frontend/.env    
    depends_on:
      - backend
      - database
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./frontend
        target: /frontend
    command: [npm,start]
    network_mode: "host"




# DEV
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pacmail-backend
    env_file:
      - ./backend/.env
    restart: always
    depends_on:
      - database
    volumes:
      - type: bind
        source: ./backend
        target: /backend
    network_mode: "host"



# STG
  database:
    image: postgres:13
    container_name: database_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432    
    volumes:
      - postgres_data:/var/lib/postgresql/data
    network_mode: "host"


volumes:
  postgres_data:
    driver: local
    name: postgres_data